In [1]:
import os

os.system('del tsne0.txt')

0

In [1]:
import glob

files_train = glob.glob('features_store_train/*.txt')
files_val = glob.glob('features_store_val/*.txt')
files_test = glob.glob('features_store_test/*.txt')
print(files_test)
print(len(files_test))


unique_labels= []

for file in files_test:
    f = file[:-4]
    f = f[-3:]
    
    unique_labels.append(f)


print(unique_labels)


['features_store_test\\ABE.txt', 'features_store_test\\ART.txt', 'features_store_test\\BAS.txt', 'features_store_test\\BLA.txt', 'features_store_test\\EBO.txt', 'features_store_test\\EOS.txt', 'features_store_test\\FGC.txt', 'features_store_test\\HAC.txt', 'features_store_test\\KSC.txt', 'features_store_test\\LYI.txt', 'features_store_test\\LYT.txt', 'features_store_test\\MMZ.txt', 'features_store_test\\MON.txt', 'features_store_test\\MYB.txt', 'features_store_test\\NGB.txt', 'features_store_test\\NGS.txt', 'features_store_test\\NIF.txt', 'features_store_test\\OTH.txt', 'features_store_test\\PEB.txt', 'features_store_test\\PLM.txt', 'features_store_test\\PMO.txt']
21
['ABE', 'ART', 'BAS', 'BLA', 'EBO', 'EOS', 'FGC', 'HAC', 'KSC', 'LYI', 'LYT', 'MMZ', 'MON', 'MYB', 'NGB', 'NGS', 'NIF', 'OTH', 'PEB', 'PLM', 'PMO']


In [2]:
readfiles = files_train+files_val+files_test

# 'range_doppler_soil_beneath_paper_no_angle2.txt', 'range_doppler_soil_beneath_paper_no_angle1.txt', 


# 'range_doppler_soil_no_angle2.txt', 'range_doppler_soil_no_angle1.txt',
# 'range_doppler_soil_plastic_no_angle1.txt', 'range_doppler_soil_plastic_no_angle2.txt',
# 'range_doppler_soil_upper_paper_no_angle1.txt', 'range_doppler_soil_upper_paper_no_angle2.txt']
# 8


print(readfiles)
print(len(readfiles))

['features_store_train\\ABE.txt', 'features_store_train\\ART1.txt', 'features_store_train\\ART10.txt', 'features_store_train\\ART11.txt', 'features_store_train\\ART12.txt', 'features_store_train\\ART13.txt', 'features_store_train\\ART14.txt', 'features_store_train\\ART15.txt', 'features_store_train\\ART2.txt', 'features_store_train\\ART3.txt', 'features_store_train\\ART4.txt', 'features_store_train\\ART5.txt', 'features_store_train\\ART6.txt', 'features_store_train\\ART7.txt', 'features_store_train\\ART8.txt', 'features_store_train\\ART9.txt', 'features_store_train\\BAS.txt', 'features_store_train\\BLA1.txt', 'features_store_train\\BLA10.txt', 'features_store_train\\BLA11.txt', 'features_store_train\\BLA12.txt', 'features_store_train\\BLA13.txt', 'features_store_train\\BLA14.txt', 'features_store_train\\BLA15.txt', 'features_store_train\\BLA2.txt', 'features_store_train\\BLA3.txt', 'features_store_train\\BLA4.txt', 'features_store_train\\BLA5.txt', 'features_store_train\\BLA6.txt', 'fe

In [3]:
import torch
print(torch.cuda.mem_get_info())

(5407899648, 6441926656)


In [4]:
import numpy as np

list_array = []
values = [0]
sum = 0

labels = []

iList = ['ABE', 'ART', 'BAS', 'BLA', 'EBO', 'EOS', 'FGC', 'HAC', 'KSC', 'LYI', 'LYT', 'MMZ', 'MON', 'MYB', 'NGB', 'NGS', 'NIF', 'OTH', 'PEB', 'PLM', 'PMO']
    
for file in readfiles:
    
    parts = file.split("\\")
    

    # Take the last part (the filename), split it by '.', and take the first part
    filename = parts[-1].split(".")[0]
    
    

    # Remove the last character (the '2') from the filename
    result = filename[:3]
    print(result)
    lbl = iList.index(result)
    
    arr = np.loadtxt(file)
    r,c = arr.shape
    sum += r
    for k in range(len(arr)):
        labels.append(lbl)
    
    list_array.append(arr)
    values.append(sum)




features = np.concatenate(list_array,axis=0)
print(features.shape)
print(values)

ABE
ART
ART
ART
ART
ART
ART
ART
ART
ART
ART
ART
ART
ART
ART
ART
BAS
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
BLA
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EBO
EOS
FGC
HAC
KSC
LYI
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
LYT
MMZ
MON
MYB
MYB
MYB
MYB
MYB
MYB
MYB
MYB
MYB
MYB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGB
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NGS
NIF
OTH
PEB
PLM
PMO
PMO
PMO
PMO
PMO
PMO
PMO
PMO
PMO
PMO
ABE
ART
BAS
BLA
EBO
EOS
FGC
HAC
KSC
LYI
LYT
MMZ
MON
MYB
NGB
NGS
NIF
OTH
PEB
PLM
PMO
ABE
ART
BAS
BLA
EBO
EOS
FGC
HAC
KSC
LYI
LYT
MMZ
MON
MYB
NGB
NGS
NIF
OTH
PEB
PLM
PMO
(171380, 512)
[0, 6, 988, 1969, 2950, 3931, 4912, 5893, 6874, 7856, 8838, 9820, 10802, 11784, 12766, 13747, 14728, 15058, 15657, 16255, 16853, 17451, 18049, 18647, 19245, 19844, 20443, 21042, 21641, 22240, 22839, 23438, 24037, 25407, 26777, 28147, 29516, 30885, 32254, 33623, 34993, 36363, 37733, 39103, 40473, 41843, 43213, 44583, 48995, 4

In [6]:
import torch
print(torch.cuda.mem_get_info())

torch.cuda.empty_cache()

ttl_gb, avl_gb = torch.cuda.mem_get_info()

print(ttl_gb/1024**3)
print(avl_gb/1024**3)

(5407899648, 6441926656)
5.0364990234375
5.99951171875


In [31]:
import numpy as np
#print(np.unique(labels))

print(len(labels))

171380


In [7]:
# import torch

# print(values)


# labels_list = []

# for i in range(len(values)-1):
#     start,end = values[i],values[i+1]
    
#     labels= [i for j in range(start,end)]
    
#     labels_list+= labels
    
    
    
    
# print(labels_list.count(22))

# print(labels)

# labels = torch.tensor(labels_list)

# print(labels)

[0, 263, 799, 1144]
0
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [34]:
print(labels)



[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [16]:

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score


# load the iris dataset as an example
data = features
print(data)

# split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.3, random_state=0)

# instantiate the model
gnb = MultinomialNB()

# train the model
gnb.fit(X_train, y_train)

# make predictions
y_predict_prob = gnb.predict_proba(X_test)
y_pred = gnb.predict(X_test)

# print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))


precision = precision_score(y_test, y_pred,average='weighted')
print('Precision: %f' % precision)

# Recall
recall = recall_score(y_test, y_pred,average='weighted')
print('Recall: %f' % recall)

# F1 score
f1 = f1_score(y_test, y_pred,average='weighted')
print('F1 score: %f' % f1)


[[0.71651632 0.97781879 0.34708932 ... 0.92703336 0.02794838 0.84355068]
 [1.09597731 1.11760628 0.48208562 ... 1.32338428 0.03347398 1.32046735]
 [0.61436075 0.85187054 0.35785317 ... 0.73546416 0.0969981  0.70483494]
 ...
 [0.33454573 1.22200036 0.         ... 0.26027849 0.         1.80577397]
 [0.49405122 1.47135484 0.         ... 0.47641554 0.         1.82957327]
 [0.52741522 0.9751038  0.         ... 0.3903214  0.         0.91199946]]
Accuracy: 94.65%
Precision: 0.951565
Recall: 0.946474
F1 score: 0.944837


In [17]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)

print(report)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       0.88      1.00      0.94      5807
           2       1.00      0.71      0.83       147
           3       0.83      1.00      0.91      3608
           4       0.93      0.99      0.96      8195
           5       1.00      0.75      0.86      1786
           6       1.00      0.77      0.87        13
           7       1.00      0.85      0.92       116
           8       1.00      0.86      0.92        14
           9       1.00      0.67      0.80        21
          10       0.99      1.00      0.99      7815
          11       1.00      0.74      0.85       875
          12       1.00      0.75      0.85      1184
          13       0.98      1.00      0.99      1992
          14       0.99      0.97      0.98      2998
          15       0.97      0.95      0.96      8950
          16       1.00      0.75      0.86      1041
          17       1.00    

In [12]:
print('fil')

fil
